version: "3.7"

services:
  app:
    build: php
    volumes:
      - ../:/app
    depends_on:
      - db
    env_file:
      - .env
    container_name: 'php-fpm'
    tty: true
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: on-failure
    container_name: sf_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: check24
      MYSQL_USER: check24
      MYSQL_PASSWORD: check24
    volumes:
      - ./data/mysql:/var/lib/mysql

  nginx:
    image: nginx:1.15.3-alpine
    container_name: 'nginx'
    restart: on-failure
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ../:/app
      - ./nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app

volumes:
  db: